#!/usr/bin/env python3
"""Generate deterministic repository topology data for Infra Observatory."""

from __future__ import annotations

import argparse
import ast
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "app" / "js" / "infra-manifest.js"
COLLECTIONS = [
    "skills",
    "changelogs",
    "gaps",
    "meta",
    "evolution",
    "evolution_daily",
    "health_reports",
    "usage",
]
RETIRED_COLLECTIONS = ["evolution"]


def _count_files(directory: Path, suffixes: set[str] | None = None) -> int:
    if not directory.exists():
        return 0
    return sum(
        1
        for path in directory.iterdir()
        if path.is_file() and (suffixes is None or path.suffix in suffixes)
    )


def _server_tool_counts() -> tuple[int, int]:
    tree = ast.parse((ROOT / "mcp-server" / "server.py").read_text())
    tools = set()
    restricted = set()
    for node in tree.body:
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            for decorator in node.decorator_list:
                func = decorator.func if isinstance(decorator, ast.Call) else decorator
                if (
                    isinstance(func, ast.Attribute)
                    and isinstance(func.value, ast.Name)
                    and func.value.id == "mcp"
                    and func.attr == "tool"
                ):
                    tools.add(node.name)
        elif isinstance(node, ast.Assign):
            names = {
                target.id for target in node.targets if isinstance(target, ast.Name)
            }
            if names & {"_WRITE_TOOLS", "_READ_ONLY_EXTRA_TOOLS"}:
                restricted.update(ast.literal_eval(node.value))
    return len(tools), len(tools - restricted)


def build_manifest() -> dict:
    hooks = json.loads((ROOT / ".codex" / "hooks.json").read_text())
    local_tools, remote_tools = _server_tool_counts()
    return {
        "schema_version": 1,
        "workflows": _count_files(ROOT / ".github" / "workflows", {".yml", ".yaml"}),
        "commands": _count_files(ROOT / "commands"),
        "scripts": _count_files(ROOT / "scripts"),
        "agents": _count_files(ROOT / "agents"),
        "hook_scripts": _count_files(ROOT / "hooks"),
        "codex_hook_events": len(hooks.get("hooks", {})),
        "local_mcp_tools": local_tools,
        "remote_mcp_tools": remote_tools,
        "active_maintenance_endpoints": 3,
        "firestore_collections": COLLECTIONS,
        "retired_firestore_collections": RETIRED_COLLECTIONS,
    }


def render(manifest: dict) -> str:
    body = json.dumps(manifest, indent=2, sort_keys=True)
    return (
        "// Generated by scripts/build_infra_manifest.py; do not edit by hand.\n"
        f"window.INFRA_MANIFEST = Object.freeze({body});\n"
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail if the committed manifest does not match the repository",
    )
    args = parser.parse_args()
    expected = render(build_manifest())
    if args.check:
        actual = OUTPUT.read_text() if OUTPUT.exists() else ""
        if actual != expected:
            raise SystemExit(
                "app/js/infra-manifest.js is stale; run "
                "python3 scripts/build_infra_manifest.py"
            )
        print("✓ Infra manifest matches repository topology")
        return
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(expected)
    print(f"✓ Wrote {OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
